apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-api
  labels:
    app: identity-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-api
  template:
    metadata:
      labels:
        app: identity-api
    spec:
      imagePullSecrets:
      - name: docker-registry-secret
      containers:
      - name: identity-api
        image: rioall77/identity.api:k8s-redis-fix
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_URLS
          value: "http://+:80"
        - name: ConnectionString
          value: "dotnetgigs-redis" 
        - name: RedisHost
          value: "dotnetgigs-redis:6379"
        - name: EventBusConnection
          value: "dotnetgigs-rabbitmq"
        - name: EventBusUserName
          value: "guest"
        - name: EventBusPassword
          value: "guest"
        - name: EventBusRetryCount
          value: "5"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
