apiVersion: v1
kind: Service
metadata:
  name: {{ template "dotnetgigs.fullname" . }}-identity-api
  labels:
    {{- include "dotnetgigs.labels" . | nindent 4 }}
    app: identity-api
spec:
  type: {{ .Values.services.identityApi.type }}
  ports:
  - port: {{ .Values.services.identityApi.port }}
    targetPort: 80
  selector:
    {{- include "dotnetgigs.selectorLabels" . | nindent 4 }}
    app: identity-api
