apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "dotnetgigs.fullname" . }}-identity-api
  labels:
    {{- include "dotnetgigs.labels" . | nindent 4 }}
    app: identity-api
spec:
  replicas: {{ .Values.replicaCount.identityApi }}
  selector:
    matchLabels:
      {{- include "dotnetgigs.selectorLabels" . | nindent 6 }}
      app: identity-api
  template:
    metadata:
      labels:
        {{- include "dotnetgigs.selectorLabels" . | nindent 8 }}
        app: identity-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
    spec:
      {{- if .Values.affinity.enabled }}
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - user.data
                topologyKey: "kubernetes.io/hostname"
      {{- end }}
      containers:
        - name: identity-api
          image: "{{ .Values.global.registry }}{{ .Values.images.identityApi.repository }}:{{ .Values.images.identityApi.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_URLS
              value: "http://+:80"
            - name: RedisHost
              value: {{ .Values.env.identityApi.RedisHost | quote }}
            - name: ConnectionString
              value: {{ .Values.env.identityApi.ConnectionString | quote }}
            - name: EventBusConnection
              value: {{ .Values.env.identityApi.EventBusConnection | quote }}
            - name: EventBusUserName
              value: "guest"
            - name: EventBusPassword
              value: "guest"
            - name: EventBusRetryCount
              value: "5"
          resources:
            {{- toYaml .Values.resources.identityApi | nindent 12 }}
          {{- if .Values.probes.enabled }}
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          {{- end }}