apiVersion: v1
kind: Service
metadata:
  name: {{ template "dotnetgigs.fullname" . }}-web
  labels:
    {{- include "dotnetgigs.labels" . | nindent 4 }}
    app: web
spec:
  type: {{ .Values.services.web.type }}
  ports:
  - port: {{ .Values.services.web.port }}
    targetPort: 80
  selector:
    {{- include "dotnetgigs.selectorLabels" . | nindent 4 }}
    app: web
