apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: default
spec:
  selector:
    app: webmvc  # Modifié de 'web' à 'webmvc' pour correspondre au label attendu
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
